theme: minima

minima:
  skin: solarized-light 
  
# classic

#remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-minimal
# minimal_mistakes_skin: "air" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: /imgs/image_vko_bw.png
description: The pages are updated intermittently. 
title: Varun Ojha, PhD

#permalink: /:title

baseurl: ""

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
