theme: jekyll-theme-minimal
logo: /imgs/image_vko_bw.png
description: It's the personal page of 
title: Varun Ojha

permalink: /:title

baseurl: ""

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
