theme: minima
#theme: jekyll-theme-minimal
# minimal_mistakes_skin: "air" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: /imgs/image_vko_bw.png
description: The pages updated intermittently. 
title: Varun Ojha

permalink: /:title

baseurl: ""

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
