theme: jekyll-theme-minimal

title: Varun Ojha

description: It's the personal page of Varun Ojha

permalink: /:title

baseurl: ""

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
